FROM node:24-alpine AS builder
WORKDIR /app

RUN npm install -g pnpm

COPY package*.json ./
RUN pnpm i
COPY . .
RUN pnpm run build

FROM nginx:1.28-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]