services:
  frontend:
    ports: 
      - "80:80"
    build: 
      context: ./frontend
      dockerfile: "dockerfile"
  backend:
    ports:
      - "3001:3001"
    build:
      context: ./backend
      dockerfile: "dockerfile"
  db:
    build:
      context: ./db
      dockerfile: "dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "tasks"
    ports:
      - "3306:3306"

