services:
  frontend:
    ports: 
      - "80:80"
    build: 
      context: ./frontend
      dockerfile: "dockerfile"
  backend:
    ports:
      - "3001:3001"
    build:
      context: ./backend
      dockerfile: "dockerfile"

