services:
  frontend:
    ports:
      - "3360" 
    build: 
      dockerfile: "./frontend/dockerfile"
    networks:
      - frontend
  backend:
    build:
      dockerfile: "./backend/dockerfile"
    depends_on:
      - frontend
    networks:
      - backend
  db:
    build:
      dockerfile: "./db/dockerfile"
    depends_on:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "tasks"
    ports:
      - "3306:3306"

networks:
  frontend:

  backend:

