FROM golang:1.25-alpine as builder

WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o backend .

# final image
FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/backend .
COPY --from=builder /app/db ./db

EXPOSE 3001

CMD ["./backend"]